services:
    emulator:
        environment:
            DISPLAY: "${DISPLAY:-:0}"
        command: [
            "-no-metrics",
            "-no-boot-anim",
            "-no-audio",
            "-accel", "on",
            "-gpu", "host",
            "-prop", "hw.keyboard=yes"
        ]
